//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        public int id { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> Возраст { get; set; }
        public string Адрес { get; set; }
        public Nullable<bool> Трудоустроен { get; set; }
    }
}
